import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Nav from '@/pages/components/Navbar'
import Main from '@/pages/components/Main'
import About from '@/pages/components/About'
import Team from '@/pages/components/Team'
export default function Home() {
  return (
    <>
      <Head>
        <title>NagatoStudio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <Nav />
          <Main />
          <About />
          <Team />
      </main>
    </>
  )
}
