import Link from 'next/link'
import Head from 'next/head'
import Nav from '@/pages/components/Navbar'
import styles from '@/styles/Join.module.css'
export default function Join() {
    return (
        <>
            <Head>
                <title>NagatoStudio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
            <Nav />
            <div className={styles.join}>
                <h1>加入我们</h1>
                <form action="https://filecdn.codereservice.top/submit.php" method="POST">
                <p>你的名字</p>
                <input type="text" id="name" required/>
                <p>你的性别</p>
                <select id="gender" required>
                    <option value="男">男</option>
                    <option value="女">女</option>
                    <option value="非二元">非二元</option>
                    <option value="MtF">MtF</option>
                    <option value="FtM">FtM</option>
                    <option value="沃尔玛购物袋">沃尔玛购物袋</option>
                </select>
                <p>你的邮箱</p>
                <input type="text" id="email" required/>
                <p>你的QQ</p>
                <input type="text" id="qq" required/>
                <p>你是从哪里知道我们的</p>
                <input type="text" id="from" required/>
                <p>你的技能</p>
                <input type="text" id="skill" required/>
                <button type="submit">提交</button>
                </form>
                <p>您的所有信息都不会被加密，并且会以明文的形式传输，NagatoStudio会向其合作机构提供您的全部信息，以便更好地泄露您的信息</p>
            </div>
            </main>
        </>
    )
}